from PyQt5.QtWidgets import *  
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from QSwitchControl import SwitchControl

def UI_design(self):

        self.setStyleSheet("background-color: white;")
        self.setFixedWidth(1150)
        self.setFixedHeight(600)

        Widget = QWidget()
        Widget.setObjectName("Widget")
        Widget.setWindowModality(Qt.NonModal)
        Widget.resize(1153, 587)
        palette = QPalette()
        Widget.setPalette(palette)
        Widget.setStyleSheet("")


        self.label = QLabel(Widget)
        self.label.setGeometry(QRect(60, 10, 251, 91))

        font = QFont()
        font.setPointSize(17)
        font.setBold(True)

        
        self.label.setFont(font)
        self.label.setTextFormat(Qt.PlainText)
        self.label.setScaledContents(False)
        self.label.setAlignment(Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.boton_iniciar = QPushButton(Widget)
        self.boton_iniciar.setGeometry(QRect(20, 110, 321, 41))

        palette = QPalette()
        self.boton_iniciar.setPalette(palette)
        font = QFont()
        font.setPointSize(12)
        self.boton_iniciar.setFont(font)
        self.boton_iniciar.setStyleSheet("")
        self.boton_iniciar.setObjectName("boton_iniciar")
        self.boton_calib = QPushButton(Widget)
        self.boton_calib.setGeometry(QRect(20, 170, 151, 41))
        palette = QPalette()

        self.boton_calib.setPalette(palette)
        font = QFont()  
        font.setPointSize(12)
        self.boton_calib.setFont(font)
        self.boton_calib.setStyleSheet("")
        self.boton_calib.setObjectName("boton_calib")
        self.boton_calib_init = QPushButton(Widget)
        self.boton_calib_init.setGeometry(QRect(190, 170, 151, 41))
        palette = QPalette()
        self.boton_calib_init.setPalette(palette)
        font = QFont()
        font.setPointSize(12)
        self.boton_calib_init.setFont(font)
        self.boton_calib_init.setStyleSheet("")
        self.boton_calib_init.setObjectName("boton_calib_init")
        self.boton_envio = QPushButton(Widget)
        self.boton_envio.setGeometry(QRect(20, 220, 151, 41))
        palette = QPalette()
        self.boton_envio.setPalette(palette)
        font = QFont()
        font.setPointSize(12)
        self.boton_envio.setFont(font)
        self.boton_envio.setStyleSheet("")
        self.boton_envio.setObjectName("boton_envio")
        self.boton_toggle_data = SwitchControl(Widget,bg_color="#777777", circle_color="#DDD", active_color="#4b86b4", animation_duration=100, checked=False, change_cursor=False)
        self.boton_toggle_data.setGeometry(QRect(220, 220, 101, 31))
        palette = QPalette()
        self.boton_toggle_data.setPalette(palette)
        font = QFont()
        font.setPointSize(14)
        self.boton_toggle_data.setFont(font)
        self.boton_toggle_data.setObjectName("boton_toggle_data")
        self.datosSerial = QTextEdit(Widget)
        self.datosSerial.setGeometry(QRect(20, 280, 321, 291))
        self.datosSerial.setObjectName("datosSerial")
        self.datosSerial.setReadOnly(True)

        self.line = QFrame(Widget)
        self.line.setGeometry(QRect(353, 30, 20, 541))
        self.line.setLineWidth(2)
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QLabel(Widget)
        self.label_2.setGeometry(QRect(400, 40, 171, 31))
        font = QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_6 = QLabel(Widget)
        self.label_6.setGeometry(QRect(390, 200, 201, 31))
        font = QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_10 = QLabel(Widget)
        self.label_10.setGeometry(QRect(390, 490, 51, 31))
        font = QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QLabel(Widget)
        self.label_11.setGeometry(QRect(380, 360, 231, 31))
        font = QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QLabel(Widget)
        self.label_12.setGeometry(QRect(390, 450, 51, 31))
        font = QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QLabel(Widget)
        self.label_13.setGeometry(QRect(390, 410, 51, 31))
        font = QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.M2_MAX_VALUE = QLineEdit(Widget)
        self.M2_MAX_VALUE.setText("0")
        self.M2_MAX_VALUE.setGeometry(QRect(450, 410, 113, 31))
        font = QFont()
        font.setPointSize(10)
        self.M2_MAX_VALUE.setFont(font)
        self.M2_MAX_VALUE.setObjectName("M2_MAX_VALUE")
        self.M2_MIN_VALUE = QLineEdit(Widget)
        self.M2_MIN_VALUE.setGeometry(QRect(450, 450, 113, 31))
        self.M2_MIN_VALUE.setText("0")
        font = QFont()
        font.setPointSize(10)
        self.M2_MIN_VALUE.setFont(font)
        self.M2_MIN_VALUE.setObjectName("M2_MIN_VALUE")
        self.M2_RANGO_VALUE = QLineEdit(Widget)
        self.M2_RANGO_VALUE.setText("0")
        self.M2_RANGO_VALUE.setGeometry(QRect(450, 490, 113, 31))
        font = QFont()
        font.setPointSize(10)
        self.M2_RANGO_VALUE.setFont(font)
        self.M2_RANGO_VALUE.setObjectName("M2_RANGO_VALUE")
        self.label_14 = QLabel(Widget)
        self.label_14.setGeometry(QRect(390, 240, 51, 31))
        font = QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.M1_RANGO_VALUE = QLineEdit(Widget)
        self.M1_RANGO_VALUE.setGeometry(QRect(450, 320, 113, 31))
        font = QFont()
        font.setPointSize(10)
        self.M1_RANGO_VALUE.setFont(font)
        self.M1_RANGO_VALUE.setObjectName("M1_RANGO_VALUE")
        self.M1_RANGO_VALUE.setText("0")
        self.M1_MAX_VALUE = QLineEdit(Widget)
        self.M1_MAX_VALUE.setGeometry(QRect(450, 240, 113, 31))
        font = QFont()
        font.setPointSize(10)
        self.M1_MAX_VALUE.setFont(font)
        self.M1_MAX_VALUE.setText("0")
        self.M1_MAX_VALUE.setObjectName("M1_MAX_VALUE")
        self.label_15 = QLabel(Widget)
        self.label_15.setGeometry(QRect(390, 320, 51, 31))
        font = QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.M1_MIN_VALUE = QLineEdit(Widget)
        self.M1_MIN_VALUE.setGeometry(QRect(450, 280, 113, 31))
        font = QFont()
        font.setPointSize(10)
        self.M1_MIN_VALUE.setFont(font)
        self.M1_MIN_VALUE.setText("0")
        self.M1_MIN_VALUE.setObjectName("M1_MIN_VALUE")
        self.label_16 = QLabel(Widget)
        self.label_16.setGeometry(QRect(390, 280, 51, 31))
        font = QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QLabel(Widget)
        self.label_17.setGeometry(QRect(390, 80, 51, 31))
        font = QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.C1_RANGO_VALUE = QLineEdit(Widget)
        self.C1_RANGO_VALUE.setGeometry(QRect(450, 160, 113, 31))
        font = QFont()
        font.setPointSize(10)
        self.C1_RANGO_VALUE.setFont(font)
        self.C1_RANGO_VALUE.setText("0")
        self.C1_RANGO_VALUE.setObjectName("C1_RANGO_VALUE")
        self.C1_MAX_VALUE = QLineEdit(Widget)
        self.C1_MAX_VALUE.setGeometry(QRect(450, 80, 113, 31))
        font = QFont()
        font.setPointSize(10)
        self.C1_MAX_VALUE.setFont(font)
        self.C1_MAX_VALUE.setObjectName("C1_MAX_VALUE")
        self.C1_MAX_VALUE.setText("0")
        self.label_18 = QLabel(Widget)
        self.label_18.setGeometry(QRect(390, 160, 51, 31))
        font = QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.C1_MIN_VALUE = QLineEdit(Widget)
        self.C1_MIN_VALUE.setGeometry(QRect(450, 120, 113, 31))
        font = QFont()
        font.setPointSize(10)
        self.C1_MIN_VALUE.setFont(font)
        self.C1_MIN_VALUE.setObjectName("C1_MIN_VALUE")
        self.C1_MIN_VALUE.setText("0")
        self.label_19 = QLabel(Widget)
        self.label_19.setGeometry(QRect(390, 120, 51, 31))
        font = QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayoutWidget = QWidget(Widget)
        self.verticalLayoutWidget.setGeometry(QRect(610, 20, 531, 551))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        # self.retranslateUi(Widget)

        _translate = QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Wearable GUI"))
        self.label.setText(_translate("Widget", "Interfaz Wearable: Extremidad Superior"))
        self.boton_iniciar.setText(_translate("Widget", "Iniciar"))
        self.boton_calib.setText(_translate("Widget", "Modo Calibración"))
        self.boton_calib_init.setText(_translate("Widget", "Iniciar calibración"))
        self.boton_envio.setText(_translate("Widget", "Modo Envío"))
        self.boton_toggle_data.setText(_translate("Widget", "Activar"))
        self.label_2.setText(_translate("Widget", "Codo: Flexión/Extensión"))
        self.label_6.setText(_translate("Widget", "Codo: Pronación/Supinación"))
        self.label_10.setText(_translate("Widget", "Rango:"))
        self.label_11.setText(_translate("Widget", "Muñeca: Flexión/Extensión"))
        self.label_12.setText(_translate("Widget", "Mínimo:"))
        self.label_13.setText(_translate("Widget", "Máximo:"))
        self.label_14.setText(_translate("Widget", "Máximo:"))
        self.label_15.setText(_translate("Widget", "Rango:"))
        self.label_16.setText(_translate("Widget", "Mínimo:"))
        self.label_17.setText(_translate("Widget", "Máximo:"))
        self.label_18.setText(_translate("Widget", "Rango:"))
        self.label_19.setText(_translate("Widget", "Mínimo:"))

        QMetaObject.connectSlotsByName(Widget)
        self.setCentralWidget(Widget)

